name: Nombre del workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  primer-job:
    runs-on: ubuntu-latest
    steps:
      - name: Primer step del primer job (echo)
        run: echo "Echo primer Job"
      - name: Step 2 Job 1 (touch file)
        run: touch test.txt
      - name: s3j1 Set text
        run: echo "Hola mundo" >> test.txt
      - name: s4j1 Read file
        run: cat test.txt
  segundo-job:
    runs-on: ubuntu-latest
    needs: [primer-job]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
                
      - name: s1j2 (LS)
        run: ls -al

      
