name: Test Environment Variables
on: push

jobs:
  echo-env:
    runs-on: ubuntu-latest

    env:
      MY_VAR: a nivel Job

    steps:
      - name: Echo Step env
        env:
          MY_VAR: a nivel Step
        run: echo "Valor= $MY_VAR"
      
      - name: Echo Job env
        run: echo "Valor= $MY_VAR"
      
      - name: Echo Github env
        run: echo "Valor= ${{ vars.MY_REPOSITORY_VARIABLE }}"