name: Test Composite Action

on: push

jobs:
  local-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7            

      - name: echo default message - composite
        uses: ./.github/actions/02-echo-message
      
      - name: echo personal message - composite
        uses: ./.github/actions/02-echo-message
        with:
          message: 'Patricia'

