name: Test Composite Action

on: push

jobs:
  local-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7            

      - name: ls
        run: ls
      - name: hello world - local action
        uses: ./.github/actions/hello-world
      - name: hola mundo - local action
        uses: ./.github/actions/hola-mundo
