name: Main

on: push

jobs:
  test-hola-mundo:
    runs-on: ubuntu-latest

    steps:
      - name: yml script
        run: |
          echo "Hola mundo" >> hola.txt
          cat hola.txt

  test-hola-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: shell script
        run: |
          chmod +x script.sh
          ./script.sh
