name: Test Composite Action

on: push

jobs:
  local-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      # - name: hello world - local action
      #   run: ./.github/actions/local/hello-world.yml
      - name: hola mundo test - local action
        run: ./.github/actions/local
