name: Nombre del workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  primer-job:
    runs-on: ubuntu-latest

    steps:
      - name: Primer step del primer job (echo)
        run: echo "Echo primer Job"

  segundo-job:
    runs-on: ubuntu-latest
    needs: primer-job
    steps:
      - name: Step 1 job 2 (LS)
        run: ls -al

      - name: s2j2 (touch file)
        run: touch test.txt

      - name: s3j2 Set text
        run: echo "Hola mundo" >> test.txt

      - name: s4j2 Read file
        run: cat test.txt
